# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - build
  - mavenbuild
  - maventest

frontend:
  tags:
    - c++_tag
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get upgrade --yes
    - apt-get --yes -m install libboost-all-dev libssl-dev libwebsocketpp-dev libsfml-dev gfortran- libcoarrays-dev- libcoarrays-openmpi-dev-
    - ldconfig -v
    - cd client/GAMEConsole
  script:
    - make all TEST=true -j4
    - ./game
  artifacts:
    paths:
      - client/GAMEConsole/

maven-build:
  stage: mavenbuild
  tags:
    - spring-backend
  script:
    - cd GameProject.zip_expanded/GameProject
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - spring-backend
  script:
    - cd GameProject.zip_expanded/GameProject
    - mvn test
  artifacts:
    paths:
      - GameProject.zip_expanded/GameProject/target/*.jar
