# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

frontend-install-dependencies:
  tags:
    - c++_tag
  stage: build
  script:
    - apt-get update --yes
    - apt-get upgrade --yes
    - apt-get --yes -m install libboost-all-dev libssl-dev libwebsocketpp-dev libsfml-dev gfortran- libcoarrays-dev- libcoarrays-openmpi-dev-

frontend-build:
  tags:
    - c++_tag
  stage: build
  script:
    - cd client/GAMEConsole
    - make test
  artifacts:
    paths:
      - client/GAMEConsole/src

# run tests using the binary built before
frontend-test:
  tags:
    - c++_tag
  stage: test
  script:
    - cd client/GAMEConsole/src
    - ./test
